/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseUpdate } from './BaseUpdate';
import {
    BaseUpdateFromJSON,
    BaseUpdateFromJSONTyped,
    BaseUpdateToJSON,
    BaseUpdateToJSONTyped,
} from './BaseUpdate';
import type { PartitionSpec } from './PartitionSpec';
import {
    PartitionSpecFromJSON,
    PartitionSpecFromJSONTyped,
    PartitionSpecToJSON,
    PartitionSpecToJSONTyped,
} from './PartitionSpec';

/**
 * 
 * @export
 * @interface AddPartitionSpecUpdate
 */
export interface AddPartitionSpecUpdate extends BaseUpdate {
    /**
     * 
     * @type {string}
     * @memberof AddPartitionSpecUpdate
     */
    action: string;
    /**
     * 
     * @type {PartitionSpec}
     * @memberof AddPartitionSpecUpdate
     */
    spec: PartitionSpec;
}

/**
 * Check if a given object implements the AddPartitionSpecUpdate interface.
 */
export function instanceOfAddPartitionSpecUpdate(value: object): value is AddPartitionSpecUpdate {
    if (!('spec' in value) || value['spec'] === undefined) return false;
    return true;
}

export function AddPartitionSpecUpdateFromJSON(json: any): AddPartitionSpecUpdate {
    return AddPartitionSpecUpdateFromJSONTyped(json, false);
}

export function AddPartitionSpecUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddPartitionSpecUpdate {
    if (json == null) {
        return json;
    }
    return {
        ...BaseUpdateFromJSONTyped(json, true),
        'action': json['action'] == null ? undefined : json['action'],
        'spec': PartitionSpecFromJSON(json['spec']),
    };
}

export function AddPartitionSpecUpdateToJSON(json: any): AddPartitionSpecUpdate {
    return AddPartitionSpecUpdateToJSONTyped(json, false);
}

export function AddPartitionSpecUpdateToJSONTyped(value?: AddPartitionSpecUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...BaseUpdateToJSONTyped(value, true),
        'action': value['action'],
        'spec': PartitionSpecToJSON(value['spec']),
    };
}

