/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseUpdate } from './BaseUpdate';
import {
    BaseUpdateFromJSON,
    BaseUpdateFromJSONTyped,
    BaseUpdateToJSON,
} from './BaseUpdate';
import type { PartitionSpec } from './PartitionSpec';
import {
    PartitionSpecFromJSON,
    PartitionSpecFromJSONTyped,
    PartitionSpecToJSON,
} from './PartitionSpec';

/**
 * 
 * @export
 * @interface AddPartitionSpecUpdate
 */
export interface AddPartitionSpecUpdate extends BaseUpdate {
    /**
     * 
     * @type {string}
     * @memberof AddPartitionSpecUpdate
     */
    action: AddPartitionSpecUpdateActionEnum;
    /**
     * 
     * @type {PartitionSpec}
     * @memberof AddPartitionSpecUpdate
     */
    spec: PartitionSpec;
}


/**
 * @export
 */
export const AddPartitionSpecUpdateActionEnum = {
    AddSpec: 'add-spec'
} as const;
export type AddPartitionSpecUpdateActionEnum = typeof AddPartitionSpecUpdateActionEnum[keyof typeof AddPartitionSpecUpdateActionEnum];


/**
 * Check if a given object implements the AddPartitionSpecUpdate interface.
 */
export function instanceOfAddPartitionSpecUpdate(value: object): boolean {
    if (!('action' in value)) return false;
    if (!('spec' in value)) return false;
    return true;
}

export function AddPartitionSpecUpdateFromJSON(json: any): AddPartitionSpecUpdate {
    return AddPartitionSpecUpdateFromJSONTyped(json, false);
}

export function AddPartitionSpecUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddPartitionSpecUpdate {
    if (json == null) {
        return json;
    }
    return {
        ...BaseUpdateFromJSONTyped(json, ignoreDiscriminator),
        'action': json['action'],
        'spec': PartitionSpecFromJSON(json['spec']),
    };
}

export function AddPartitionSpecUpdateToJSON(value?: AddPartitionSpecUpdate | null): any {
    if (value == null) {
        return value;
    }
    return {
        ...BaseUpdateToJSON(value),
        'action': value['action'],
        'spec': PartitionSpecToJSON(value['spec']),
    };
}

