/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseUpdate } from './BaseUpdate';
import {
    BaseUpdateFromJSON,
    BaseUpdateFromJSONTyped,
    BaseUpdateToJSON,
} from './BaseUpdate';
import type { Schema } from './Schema';
import {
    SchemaFromJSON,
    SchemaFromJSONTyped,
    SchemaToJSON,
} from './Schema';

/**
 * 
 * @export
 * @interface AddSchemaUpdate
 */
export interface AddSchemaUpdate extends BaseUpdate {
    /**
     * 
     * @type {string}
     * @memberof AddSchemaUpdate
     */
    action: AddSchemaUpdateActionEnum;
    /**
     * 
     * @type {Schema}
     * @memberof AddSchemaUpdate
     */
    schema: Schema;
    /**
     * The highest assigned column ID for the table. This is used to ensure columns are always assigned an unused ID when evolving schemas. When omitted, it will be computed on the server side.
     * @type {number}
     * @memberof AddSchemaUpdate
     */
    lastColumnId?: number;
}


/**
 * @export
 */
export const AddSchemaUpdateActionEnum = {
    AddSchema: 'add-schema'
} as const;
export type AddSchemaUpdateActionEnum = typeof AddSchemaUpdateActionEnum[keyof typeof AddSchemaUpdateActionEnum];


/**
 * Check if a given object implements the AddSchemaUpdate interface.
 */
export function instanceOfAddSchemaUpdate(value: object): boolean {
    if (!('action' in value)) return false;
    if (!('schema' in value)) return false;
    return true;
}

export function AddSchemaUpdateFromJSON(json: any): AddSchemaUpdate {
    return AddSchemaUpdateFromJSONTyped(json, false);
}

export function AddSchemaUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddSchemaUpdate {
    if (json == null) {
        return json;
    }
    return {
        ...BaseUpdateFromJSONTyped(json, ignoreDiscriminator),
        'action': json['action'],
        'schema': SchemaFromJSON(json['schema']),
        'lastColumnId': json['last-column-id'] == null ? undefined : json['last-column-id'],
    };
}

export function AddSchemaUpdateToJSON(value?: AddSchemaUpdate | null): any {
    if (value == null) {
        return value;
    }
    return {
        ...BaseUpdateToJSON(value),
        'action': value['action'],
        'schema': SchemaToJSON(value['schema']),
        'last-column-id': value['lastColumnId'],
    };
}

