/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TableRequirement } from './TableRequirement';
import {
    TableRequirementFromJSON,
    TableRequirementFromJSONTyped,
    TableRequirementToJSON,
} from './TableRequirement';

/**
 * The table's last assigned partition id must match the requirement's `last-assigned-partition-id`
 * @export
 * @interface AssertLastAssignedPartitionId
 */
export interface AssertLastAssignedPartitionId extends TableRequirement {
    /**
     * 
     * @type {string}
     * @memberof AssertLastAssignedPartitionId
     */
    type: AssertLastAssignedPartitionIdTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof AssertLastAssignedPartitionId
     */
    lastAssignedPartitionId: number;
}


/**
 * @export
 */
export const AssertLastAssignedPartitionIdTypeEnum = {
    AssertLastAssignedPartitionId: 'assert-last-assigned-partition-id'
} as const;
export type AssertLastAssignedPartitionIdTypeEnum = typeof AssertLastAssignedPartitionIdTypeEnum[keyof typeof AssertLastAssignedPartitionIdTypeEnum];


/**
 * Check if a given object implements the AssertLastAssignedPartitionId interface.
 */
export function instanceOfAssertLastAssignedPartitionId(value: object): boolean {
    if (!('type' in value)) return false;
    if (!('lastAssignedPartitionId' in value)) return false;
    return true;
}

export function AssertLastAssignedPartitionIdFromJSON(json: any): AssertLastAssignedPartitionId {
    return AssertLastAssignedPartitionIdFromJSONTyped(json, false);
}

export function AssertLastAssignedPartitionIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssertLastAssignedPartitionId {
    if (json == null) {
        return json;
    }
    return {
        ...TableRequirementFromJSONTyped(json, ignoreDiscriminator),
        'type': json['type'],
        'lastAssignedPartitionId': json['last-assigned-partition-id'],
    };
}

export function AssertLastAssignedPartitionIdToJSON(value?: AssertLastAssignedPartitionId | null): any {
    if (value == null) {
        return value;
    }
    return {
        ...TableRequirementToJSON(value),
        'type': value['type'],
        'last-assigned-partition-id': value['lastAssignedPartitionId'],
    };
}

