/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TableRequirement } from './TableRequirement';
import {
    TableRequirementFromJSON,
    TableRequirementFromJSONTyped,
    TableRequirementToJSON,
} from './TableRequirement';

/**
 * The table's default sort order id must match the requirement's `default-sort-order-id`
 * @export
 * @interface AssertDefaultSortOrderId
 */
export interface AssertDefaultSortOrderId extends TableRequirement {
    /**
     * 
     * @type {string}
     * @memberof AssertDefaultSortOrderId
     */
    type: AssertDefaultSortOrderIdTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof AssertDefaultSortOrderId
     */
    defaultSortOrderId: number;
}


/**
 * @export
 */
export const AssertDefaultSortOrderIdTypeEnum = {
    AssertDefaultSortOrderId: 'assert-default-sort-order-id'
} as const;
export type AssertDefaultSortOrderIdTypeEnum = typeof AssertDefaultSortOrderIdTypeEnum[keyof typeof AssertDefaultSortOrderIdTypeEnum];


/**
 * Check if a given object implements the AssertDefaultSortOrderId interface.
 */
export function instanceOfAssertDefaultSortOrderId(value: object): boolean {
    if (!('type' in value)) return false;
    if (!('defaultSortOrderId' in value)) return false;
    return true;
}

export function AssertDefaultSortOrderIdFromJSON(json: any): AssertDefaultSortOrderId {
    return AssertDefaultSortOrderIdFromJSONTyped(json, false);
}

export function AssertDefaultSortOrderIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssertDefaultSortOrderId {
    if (json == null) {
        return json;
    }
    return {
        ...TableRequirementFromJSONTyped(json, ignoreDiscriminator),
        'type': json['type'],
        'defaultSortOrderId': json['default-sort-order-id'],
    };
}

export function AssertDefaultSortOrderIdToJSON(value?: AssertDefaultSortOrderId | null): any {
    if (value == null) {
        return value;
    }
    return {
        ...TableRequirementToJSON(value),
        'type': value['type'],
        'default-sort-order-id': value['defaultSortOrderId'],
    };
}

