/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TableRequirement } from './TableRequirement';
import {
    TableRequirementFromJSON,
    TableRequirementFromJSONTyped,
    TableRequirementToJSON,
} from './TableRequirement';

/**
 * The table's last assigned column id must match the requirement's `last-assigned-field-id`
 * @export
 * @interface AssertLastAssignedFieldId
 */
export interface AssertLastAssignedFieldId extends TableRequirement {
    /**
     * 
     * @type {string}
     * @memberof AssertLastAssignedFieldId
     */
    type: AssertLastAssignedFieldIdTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof AssertLastAssignedFieldId
     */
    lastAssignedFieldId: number;
}


/**
 * @export
 */
export const AssertLastAssignedFieldIdTypeEnum = {
    AssertLastAssignedFieldId: 'assert-last-assigned-field-id'
} as const;
export type AssertLastAssignedFieldIdTypeEnum = typeof AssertLastAssignedFieldIdTypeEnum[keyof typeof AssertLastAssignedFieldIdTypeEnum];


/**
 * Check if a given object implements the AssertLastAssignedFieldId interface.
 */
export function instanceOfAssertLastAssignedFieldId(value: object): boolean {
    if (!('type' in value)) return false;
    if (!('lastAssignedFieldId' in value)) return false;
    return true;
}

export function AssertLastAssignedFieldIdFromJSON(json: any): AssertLastAssignedFieldId {
    return AssertLastAssignedFieldIdFromJSONTyped(json, false);
}

export function AssertLastAssignedFieldIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssertLastAssignedFieldId {
    if (json == null) {
        return json;
    }
    return {
        ...TableRequirementFromJSONTyped(json, ignoreDiscriminator),
        'type': json['type'],
        'lastAssignedFieldId': json['last-assigned-field-id'],
    };
}

export function AssertLastAssignedFieldIdToJSON(value?: AssertLastAssignedFieldId | null): any {
    if (value == null) {
        return value;
    }
    return {
        ...TableRequirementToJSON(value),
        'type': value['type'],
        'last-assigned-field-id': value['lastAssignedFieldId'],
    };
}

