/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TableRequirement } from './TableRequirement';
import {
    TableRequirementFromJSON,
    TableRequirementFromJSONTyped,
    TableRequirementToJSON,
    TableRequirementToJSONTyped,
} from './TableRequirement';

/**
 * The table UUID must match the requirement's `uuid`
 * @export
 * @interface AssertTableUUID
 */
export interface AssertTableUUID extends TableRequirement {
    /**
     * 
     * @type {string}
     * @memberof AssertTableUUID
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof AssertTableUUID
     */
    uuid: string;
}

/**
 * Check if a given object implements the AssertTableUUID interface.
 */
export function instanceOfAssertTableUUID(value: object): value is AssertTableUUID {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('uuid' in value) || value['uuid'] === undefined) return false;
    return true;
}

export function AssertTableUUIDFromJSON(json: any): AssertTableUUID {
    return AssertTableUUIDFromJSONTyped(json, false);
}

export function AssertTableUUIDFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssertTableUUID {
    if (json == null) {
        return json;
    }
    return {
        ...TableRequirementFromJSONTyped(json, true),
        'type': json['type'],
        'uuid': json['uuid'],
    };
}

export function AssertTableUUIDToJSON(json: any): AssertTableUUID {
    return AssertTableUUIDToJSONTyped(json, false);
}

export function AssertTableUUIDToJSONTyped(value?: AssertTableUUID | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...TableRequirementToJSONTyped(value, true),
        'type': value['type'],
        'uuid': value['uuid'],
    };
}

