/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TableRequirement } from './TableRequirement';
import {
    TableRequirementFromJSON,
    TableRequirementFromJSONTyped,
    TableRequirementToJSON,
} from './TableRequirement';

/**
 * The table's current schema id must match the requirement's `current-schema-id`
 * @export
 * @interface AssertCurrentSchemaId
 */
export interface AssertCurrentSchemaId extends TableRequirement {
    /**
     * 
     * @type {string}
     * @memberof AssertCurrentSchemaId
     */
    type: AssertCurrentSchemaIdTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof AssertCurrentSchemaId
     */
    currentSchemaId: number;
}


/**
 * @export
 */
export const AssertCurrentSchemaIdTypeEnum = {
    AssertCurrentSchemaId: 'assert-current-schema-id'
} as const;
export type AssertCurrentSchemaIdTypeEnum = typeof AssertCurrentSchemaIdTypeEnum[keyof typeof AssertCurrentSchemaIdTypeEnum];


/**
 * Check if a given object implements the AssertCurrentSchemaId interface.
 */
export function instanceOfAssertCurrentSchemaId(value: object): boolean {
    if (!('type' in value)) return false;
    if (!('currentSchemaId' in value)) return false;
    return true;
}

export function AssertCurrentSchemaIdFromJSON(json: any): AssertCurrentSchemaId {
    return AssertCurrentSchemaIdFromJSONTyped(json, false);
}

export function AssertCurrentSchemaIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssertCurrentSchemaId {
    if (json == null) {
        return json;
    }
    return {
        ...TableRequirementFromJSONTyped(json, ignoreDiscriminator),
        'type': json['type'],
        'currentSchemaId': json['current-schema-id'],
    };
}

export function AssertCurrentSchemaIdToJSON(value?: AssertCurrentSchemaId | null): any {
    if (value == null) {
        return value;
    }
    return {
        ...TableRequirementToJSON(value),
        'type': value['type'],
        'current-schema-id': value['currentSchemaId'],
    };
}

