/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TableRequirement } from './TableRequirement';
import {
    TableRequirementFromJSON,
    TableRequirementFromJSONTyped,
    TableRequirementToJSON,
    TableRequirementToJSONTyped,
} from './TableRequirement';

/**
 * The table branch or tag identified by the requirement's `ref` must reference the requirement's `snapshot-id`; if `snapshot-id` is `null` or missing, the ref must not already exist
 * @export
 * @interface AssertRefSnapshotId
 */
export interface AssertRefSnapshotId extends TableRequirement {
    /**
     * 
     * @type {string}
     * @memberof AssertRefSnapshotId
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof AssertRefSnapshotId
     */
    ref: string;
    /**
     * 
     * @type {number}
     * @memberof AssertRefSnapshotId
     */
    snapshotId: number;
}

/**
 * Check if a given object implements the AssertRefSnapshotId interface.
 */
export function instanceOfAssertRefSnapshotId(value: object): value is AssertRefSnapshotId {
    if (!('ref' in value) || value['ref'] === undefined) return false;
    if (!('snapshotId' in value) || value['snapshotId'] === undefined) return false;
    return true;
}

export function AssertRefSnapshotIdFromJSON(json: any): AssertRefSnapshotId {
    return AssertRefSnapshotIdFromJSONTyped(json, false);
}

export function AssertRefSnapshotIdFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssertRefSnapshotId {
    if (json == null) {
        return json;
    }
    return {
        ...TableRequirementFromJSONTyped(json, true),
        'type': json['type'] == null ? undefined : json['type'],
        'ref': json['ref'],
        'snapshotId': json['snapshot-id'],
    };
}

export function AssertRefSnapshotIdToJSON(json: any): AssertRefSnapshotId {
    return AssertRefSnapshotIdToJSONTyped(json, false);
}

export function AssertRefSnapshotIdToJSONTyped(value?: AssertRefSnapshotId | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...TableRequirementToJSONTyped(value, true),
        'type': value['type'],
        'ref': value['ref'],
        'snapshot-id': value['snapshotId'],
    };
}

