/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PlanStatus } from './PlanStatus';
import {
    PlanStatusFromJSON,
    PlanStatusFromJSONTyped,
    PlanStatusToJSON,
    PlanStatusToJSONTyped,
} from './PlanStatus';

/**
 * 
 * @export
 * @interface AsyncPlanningResult
 */
export interface AsyncPlanningResult {
    /**
     * 
     * @type {PlanStatus}
     * @memberof AsyncPlanningResult
     */
    status: PlanStatus;
    /**
     * ID used to track a planning request
     * @type {string}
     * @memberof AsyncPlanningResult
     */
    planId?: string;
}



/**
 * Check if a given object implements the AsyncPlanningResult interface.
 */
export function instanceOfAsyncPlanningResult(value: object): value is AsyncPlanningResult {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function AsyncPlanningResultFromJSON(json: any): AsyncPlanningResult {
    return AsyncPlanningResultFromJSONTyped(json, false);
}

export function AsyncPlanningResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): AsyncPlanningResult {
    if (json == null) {
        return json;
    }
    return {
        
        'status': PlanStatusFromJSON(json['status']),
        'planId': json['plan-id'] == null ? undefined : json['plan-id'],
    };
}

export function AsyncPlanningResultToJSON(json: any): AsyncPlanningResult {
    return AsyncPlanningResultToJSONTyped(json, false);
}

export function AsyncPlanningResultToJSONTyped(value?: AsyncPlanningResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': PlanStatusToJSON(value['status']),
        'plan-id': value['planId'],
    };
}

