/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileScanTask } from './FileScanTask';
import {
    FileScanTaskFromJSON,
    FileScanTaskFromJSONTyped,
    FileScanTaskToJSON,
    FileScanTaskToJSONTyped,
} from './FileScanTask';
import type { DeleteFile } from './DeleteFile';
import {
    DeleteFileFromJSON,
    DeleteFileFromJSONTyped,
    DeleteFileToJSON,
    DeleteFileToJSONTyped,
} from './DeleteFile';
import type { PlanStatus } from './PlanStatus';
import {
    PlanStatusFromJSON,
    PlanStatusFromJSONTyped,
    PlanStatusToJSON,
    PlanStatusToJSONTyped,
} from './PlanStatus';

/**
 * 
 * @export
 * @interface CompletedPlanningWithIDResult
 */
export interface CompletedPlanningWithIDResult {
    /**
     * Delete files referenced by file scan tasks
     * @type {Array<DeleteFile>}
     * @memberof CompletedPlanningWithIDResult
     */
    deleteFiles?: Array<DeleteFile>;
    /**
     * 
     * @type {Array<FileScanTask>}
     * @memberof CompletedPlanningWithIDResult
     */
    fileScanTasks?: Array<FileScanTask>;
    /**
     * 
     * @type {Array<string>}
     * @memberof CompletedPlanningWithIDResult
     */
    planTasks?: Array<string>;
    /**
     * 
     * @type {PlanStatus}
     * @memberof CompletedPlanningWithIDResult
     */
    status: PlanStatus;
    /**
     * ID used to track a planning request
     * @type {string}
     * @memberof CompletedPlanningWithIDResult
     */
    planId?: string;
}



/**
 * Check if a given object implements the CompletedPlanningWithIDResult interface.
 */
export function instanceOfCompletedPlanningWithIDResult(value: object): value is CompletedPlanningWithIDResult {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function CompletedPlanningWithIDResultFromJSON(json: any): CompletedPlanningWithIDResult {
    return CompletedPlanningWithIDResultFromJSONTyped(json, false);
}

export function CompletedPlanningWithIDResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CompletedPlanningWithIDResult {
    if (json == null) {
        return json;
    }
    return {
        
        'deleteFiles': json['delete-files'] == null ? undefined : ((json['delete-files'] as Array<any>).map(DeleteFileFromJSON)),
        'fileScanTasks': json['file-scan-tasks'] == null ? undefined : ((json['file-scan-tasks'] as Array<any>).map(FileScanTaskFromJSON)),
        'planTasks': json['plan-tasks'] == null ? undefined : json['plan-tasks'],
        'status': PlanStatusFromJSON(json['status']),
        'planId': json['plan-id'] == null ? undefined : json['plan-id'],
    };
}

export function CompletedPlanningWithIDResultToJSON(json: any): CompletedPlanningWithIDResult {
    return CompletedPlanningWithIDResultToJSONTyped(json, false);
}

export function CompletedPlanningWithIDResultToJSONTyped(value?: CompletedPlanningWithIDResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'delete-files': value['deleteFiles'] == null ? undefined : ((value['deleteFiles'] as Array<any>).map(DeleteFileToJSON)),
        'file-scan-tasks': value['fileScanTasks'] == null ? undefined : ((value['fileScanTasks'] as Array<any>).map(FileScanTaskToJSON)),
        'plan-tasks': value['planTasks'],
        'status': PlanStatusToJSON(value['status']),
        'plan-id': value['planId'],
    };
}

