/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CounterResult
 */
export interface CounterResult {
    /**
     * 
     * @type {string}
     * @memberof CounterResult
     */
    unit: string;
    /**
     * 
     * @type {number}
     * @memberof CounterResult
     */
    value: number;
}

/**
 * Check if a given object implements the CounterResult interface.
 */
export function instanceOfCounterResult(value: object): boolean {
    if (!('unit' in value)) return false;
    if (!('value' in value)) return false;
    return true;
}

export function CounterResultFromJSON(json: any): CounterResult {
    return CounterResultFromJSONTyped(json, false);
}

export function CounterResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): CounterResult {
    if (json == null) {
        return json;
    }
    return {
        
        'unit': json['unit'],
        'value': json['value'],
    };
}

export function CounterResultToJSON(value?: CounterResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'unit': value['unit'],
        'value': value['value'],
    };
}

