/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateNamespaceRequest
 */
export interface CreateNamespaceRequest {
    /**
     * Reference to one or more levels of a namespace
     * @type {Array<string>}
     * @memberof CreateNamespaceRequest
     */
    namespace: Array<string>;
    /**
     * Configured string to string map of properties for the namespace
     * @type {{ [key: string]: string; }}
     * @memberof CreateNamespaceRequest
     */
    properties?: { [key: string]: string; };
}

/**
 * Check if a given object implements the CreateNamespaceRequest interface.
 */
export function instanceOfCreateNamespaceRequest(value: object): value is CreateNamespaceRequest {
    if (!('namespace' in value) || value['namespace'] === undefined) return false;
    return true;
}

export function CreateNamespaceRequestFromJSON(json: any): CreateNamespaceRequest {
    return CreateNamespaceRequestFromJSONTyped(json, false);
}

export function CreateNamespaceRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateNamespaceRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'namespace': json['namespace'],
        'properties': json['properties'] == null ? undefined : json['properties'],
    };
}

export function CreateNamespaceRequestToJSON(json: any): CreateNamespaceRequest {
    return CreateNamespaceRequestToJSONTyped(json, false);
}

export function CreateNamespaceRequestToJSONTyped(value?: CreateNamespaceRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'namespace': value['namespace'],
        'properties': value['properties'],
    };
}

