/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseUpdate } from './BaseUpdate';
import {
    BaseUpdateFromJSON,
    BaseUpdateFromJSONTyped,
    BaseUpdateToJSON,
    BaseUpdateToJSONTyped,
} from './BaseUpdate';

/**
 * 
 * @export
 * @interface EnableRowLineageUpdate
 */
export interface EnableRowLineageUpdate extends BaseUpdate {
    /**
     * 
     * @type {string}
     * @memberof EnableRowLineageUpdate
     */
    action: string;
}

/**
 * Check if a given object implements the EnableRowLineageUpdate interface.
 */
export function instanceOfEnableRowLineageUpdate(value: object): value is EnableRowLineageUpdate {
    return true;
}

export function EnableRowLineageUpdateFromJSON(json: any): EnableRowLineageUpdate {
    return EnableRowLineageUpdateFromJSONTyped(json, false);
}

export function EnableRowLineageUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnableRowLineageUpdate {
    if (json == null) {
        return json;
    }
    return {
        ...BaseUpdateFromJSONTyped(json, true),
        'action': json['action'] == null ? undefined : json['action'],
    };
}

export function EnableRowLineageUpdateToJSON(json: any): EnableRowLineageUpdate {
    return EnableRowLineageUpdateToJSONTyped(json, false);
}

export function EnableRowLineageUpdateToJSONTyped(value?: EnableRowLineageUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...BaseUpdateToJSONTyped(value, true),
        'action': value['action'],
    };
}

