/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PrimitiveTypeValue } from './PrimitiveTypeValue';
import {
    PrimitiveTypeValueFromJSON,
    PrimitiveTypeValueFromJSONTyped,
    PrimitiveTypeValueToJSON,
} from './PrimitiveTypeValue';
import type { ContentFile } from './ContentFile';
import {
    ContentFileFromJSON,
    ContentFileFromJSONTyped,
    ContentFileToJSON,
} from './ContentFile';
import type { FileFormat } from './FileFormat';
import {
    FileFormatFromJSON,
    FileFormatFromJSONTyped,
    FileFormatToJSON,
} from './FileFormat';

/**
 * 
 * @export
 * @interface EqualityDeleteFile
 */
export interface EqualityDeleteFile extends ContentFile {
    /**
     * 
     * @type {string}
     * @memberof EqualityDeleteFile
     */
    content: EqualityDeleteFileContentEnum;
    /**
     * List of equality field IDs
     * @type {Array<number>}
     * @memberof EqualityDeleteFile
     */
    equalityIds?: Array<number>;
}


/**
 * @export
 */
export const EqualityDeleteFileContentEnum = {
    EqualityDeletes: 'equality-deletes'
} as const;
export type EqualityDeleteFileContentEnum = typeof EqualityDeleteFileContentEnum[keyof typeof EqualityDeleteFileContentEnum];


/**
 * Check if a given object implements the EqualityDeleteFile interface.
 */
export function instanceOfEqualityDeleteFile(value: object): boolean {
    if (!('content' in value)) return false;
    return true;
}

export function EqualityDeleteFileFromJSON(json: any): EqualityDeleteFile {
    return EqualityDeleteFileFromJSONTyped(json, false);
}

export function EqualityDeleteFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): EqualityDeleteFile {
    if (json == null) {
        return json;
    }
    return {
        ...ContentFileFromJSONTyped(json, ignoreDiscriminator),
        'content': json['content'],
        'equalityIds': json['equality-ids'] == null ? undefined : json['equality-ids'],
    };
}

export function EqualityDeleteFileToJSON(value?: EqualityDeleteFile | null): any {
    if (value == null) {
        return value;
    }
    return {
        ...ContentFileToJSON(value),
        'content': value['content'],
        'equality-ids': value['equalityIds'],
    };
}

