/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FalseExpression
 */
export interface FalseExpression {
    /**
     * 
     * @type {string}
     * @memberof FalseExpression
     */
    type: string;
}

/**
 * Check if a given object implements the FalseExpression interface.
 */
export function instanceOfFalseExpression(value: object): value is FalseExpression {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function FalseExpressionFromJSON(json: any): FalseExpression {
    return FalseExpressionFromJSONTyped(json, false);
}

export function FalseExpressionFromJSONTyped(json: any, ignoreDiscriminator: boolean): FalseExpression {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function FalseExpressionToJSON(json: any): FalseExpression {
    return FalseExpressionToJSONTyped(json, false);
}

export function FalseExpressionToJSONTyped(value?: FalseExpression | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
    };
}

