/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FileScanTask } from './FileScanTask';
import {
    FileScanTaskFromJSON,
    FileScanTaskFromJSONTyped,
    FileScanTaskToJSON,
    FileScanTaskToJSONTyped,
} from './FileScanTask';
import type { DeleteFile } from './DeleteFile';
import {
    DeleteFileFromJSON,
    DeleteFileFromJSONTyped,
    DeleteFileToJSON,
    DeleteFileToJSONTyped,
} from './DeleteFile';

/**
 * Response schema for fetchScanTasks
 * @export
 * @interface FetchScanTasksResult
 */
export interface FetchScanTasksResult {
    /**
     * Delete files referenced by file scan tasks
     * @type {Array<DeleteFile>}
     * @memberof FetchScanTasksResult
     */
    deleteFiles?: Array<DeleteFile>;
    /**
     * 
     * @type {Array<FileScanTask>}
     * @memberof FetchScanTasksResult
     */
    fileScanTasks?: Array<FileScanTask>;
    /**
     * 
     * @type {Array<string>}
     * @memberof FetchScanTasksResult
     */
    planTasks?: Array<string>;
}

/**
 * Check if a given object implements the FetchScanTasksResult interface.
 */
export function instanceOfFetchScanTasksResult(value: object): value is FetchScanTasksResult {
    return true;
}

export function FetchScanTasksResultFromJSON(json: any): FetchScanTasksResult {
    return FetchScanTasksResultFromJSONTyped(json, false);
}

export function FetchScanTasksResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): FetchScanTasksResult {
    if (json == null) {
        return json;
    }
    return {
        
        'deleteFiles': json['delete-files'] == null ? undefined : ((json['delete-files'] as Array<any>).map(DeleteFileFromJSON)),
        'fileScanTasks': json['file-scan-tasks'] == null ? undefined : ((json['file-scan-tasks'] as Array<any>).map(FileScanTaskFromJSON)),
        'planTasks': json['plan-tasks'] == null ? undefined : json['plan-tasks'],
    };
}

export function FetchScanTasksResultToJSON(json: any): FetchScanTasksResult {
    return FetchScanTasksResultToJSONTyped(json, false);
}

export function FetchScanTasksResultToJSONTyped(value?: FetchScanTasksResult | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'delete-files': value['deleteFiles'] == null ? undefined : ((value['deleteFiles'] as Array<any>).map(DeleteFileToJSON)),
        'file-scan-tasks': value['fileScanTasks'] == null ? undefined : ((value['fileScanTasks'] as Array<any>).map(FileScanTaskToJSON)),
        'plan-tasks': value['planTasks'],
    };
}

