/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const FileFormat = {
    Avro: 'avro',
    Orc: 'orc',
    Parquet: 'parquet',
    Puffin: 'puffin'
} as const;
export type FileFormat = typeof FileFormat[keyof typeof FileFormat];


export function instanceOfFileFormat(value: any): boolean {
    for (const key in FileFormat) {
        if (Object.prototype.hasOwnProperty.call(FileFormat, key)) {
            if (FileFormat[key as keyof typeof FileFormat] === value) {
                return true;
            }
        }
    }
    return false;
}

export function FileFormatFromJSON(json: any): FileFormat {
    return FileFormatFromJSONTyped(json, false);
}

export function FileFormatFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileFormat {
    return json as FileFormat;
}

export function FileFormatToJSON(value?: FileFormat | null): any {
    return value as any;
}

export function FileFormatToJSONTyped(value: any, ignoreDiscriminator: boolean): FileFormat {
    return value as FileFormat;
}

