/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const NullOrder = {
    First: 'nulls-first',
    Last: 'nulls-last'
} as const;
export type NullOrder = typeof NullOrder[keyof typeof NullOrder];


export function instanceOfNullOrder(value: any): boolean {
    return Object.values(NullOrder).includes(value);
}

export function NullOrderFromJSON(json: any): NullOrder {
    return NullOrderFromJSONTyped(json, false);
}

export function NullOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): NullOrder {
    return json as NullOrder;
}

export function NullOrderToJSON(value?: NullOrder | null): any {
    return value as any;
}

