/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const NullOrder = {
    NullsFirst: 'nulls-first',
    NullsLast: 'nulls-last'
} as const;
export type NullOrder = typeof NullOrder[keyof typeof NullOrder];


export function instanceOfNullOrder(value: any): boolean {
    for (const key in NullOrder) {
        if (Object.prototype.hasOwnProperty.call(NullOrder, key)) {
            if (NullOrder[key as keyof typeof NullOrder] === value) {
                return true;
            }
        }
    }
    return false;
}

export function NullOrderFromJSON(json: any): NullOrder {
    return NullOrderFromJSONTyped(json, false);
}

export function NullOrderFromJSONTyped(json: any, ignoreDiscriminator: boolean): NullOrder {
    return json as NullOrder;
}

export function NullOrderToJSON(value?: NullOrder | null): any {
    return value as any;
}

export function NullOrderToJSONTyped(value: any, ignoreDiscriminator: boolean): NullOrder {
    return value as NullOrder;
}

