/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PartitionField
 */
export interface PartitionField {
    /**
     * 
     * @type {number}
     * @memberof PartitionField
     */
    fieldId?: number;
    /**
     * 
     * @type {number}
     * @memberof PartitionField
     */
    sourceId: number;
    /**
     * 
     * @type {string}
     * @memberof PartitionField
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PartitionField
     */
    transform: string;
}

/**
 * Check if a given object implements the PartitionField interface.
 */
export function instanceOfPartitionField(value: object): value is PartitionField {
    if (!('sourceId' in value) || value['sourceId'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('transform' in value) || value['transform'] === undefined) return false;
    return true;
}

export function PartitionFieldFromJSON(json: any): PartitionField {
    return PartitionFieldFromJSONTyped(json, false);
}

export function PartitionFieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartitionField {
    if (json == null) {
        return json;
    }
    return {
        
        'fieldId': json['field-id'] == null ? undefined : json['field-id'],
        'sourceId': json['source-id'],
        'name': json['name'],
        'transform': json['transform'],
    };
}

export function PartitionFieldToJSON(json: any): PartitionField {
    return PartitionFieldToJSONTyped(json, false);
}

export function PartitionFieldToJSONTyped(value?: PartitionField | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'field-id': value['fieldId'],
        'source-id': value['sourceId'],
        'name': value['name'],
        'transform': value['transform'],
    };
}

