/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PartitionStatisticsFile
 */
export interface PartitionStatisticsFile {
    /**
     * 
     * @type {number}
     * @memberof PartitionStatisticsFile
     */
    snapshotId: number;
    /**
     * 
     * @type {string}
     * @memberof PartitionStatisticsFile
     */
    statisticsPath: string;
    /**
     * 
     * @type {number}
     * @memberof PartitionStatisticsFile
     */
    fileSizeInBytes: number;
}

/**
 * Check if a given object implements the PartitionStatisticsFile interface.
 */
export function instanceOfPartitionStatisticsFile(value: object): value is PartitionStatisticsFile {
    if (!('snapshotId' in value) || value['snapshotId'] === undefined) return false;
    if (!('statisticsPath' in value) || value['statisticsPath'] === undefined) return false;
    if (!('fileSizeInBytes' in value) || value['fileSizeInBytes'] === undefined) return false;
    return true;
}

export function PartitionStatisticsFileFromJSON(json: any): PartitionStatisticsFile {
    return PartitionStatisticsFileFromJSONTyped(json, false);
}

export function PartitionStatisticsFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): PartitionStatisticsFile {
    if (json == null) {
        return json;
    }
    return {
        
        'snapshotId': json['snapshot-id'],
        'statisticsPath': json['statistics-path'],
        'fileSizeInBytes': json['file-size-in-bytes'],
    };
}

export function PartitionStatisticsFileToJSON(json: any): PartitionStatisticsFile {
    return PartitionStatisticsFileToJSONTyped(json, false);
}

export function PartitionStatisticsFileToJSONTyped(value?: PartitionStatisticsFile | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'snapshot-id': value['snapshotId'],
        'statistics-path': value['statisticsPath'],
        'file-size-in-bytes': value['fileSizeInBytes'],
    };
}

