/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PrimitiveTypeValue } from './PrimitiveTypeValue';
import {
    PrimitiveTypeValueFromJSON,
    PrimitiveTypeValueFromJSONTyped,
    PrimitiveTypeValueToJSON,
} from './PrimitiveTypeValue';
import type { ContentFile } from './ContentFile';
import {
    ContentFileFromJSON,
    ContentFileFromJSONTyped,
    ContentFileToJSON,
} from './ContentFile';
import type { FileFormat } from './FileFormat';
import {
    FileFormatFromJSON,
    FileFormatFromJSONTyped,
    FileFormatToJSON,
} from './FileFormat';

/**
 * 
 * @export
 * @interface PositionDeleteFile
 */
export interface PositionDeleteFile extends ContentFile {
    /**
     * 
     * @type {string}
     * @memberof PositionDeleteFile
     */
    content: PositionDeleteFileContentEnum;
}


/**
 * @export
 */
export const PositionDeleteFileContentEnum = {
    PositionDeletes: 'position-deletes'
} as const;
export type PositionDeleteFileContentEnum = typeof PositionDeleteFileContentEnum[keyof typeof PositionDeleteFileContentEnum];


/**
 * Check if a given object implements the PositionDeleteFile interface.
 */
export function instanceOfPositionDeleteFile(value: object): boolean {
    if (!('content' in value)) return false;
    return true;
}

export function PositionDeleteFileFromJSON(json: any): PositionDeleteFile {
    return PositionDeleteFileFromJSONTyped(json, false);
}

export function PositionDeleteFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): PositionDeleteFile {
    if (json == null) {
        return json;
    }
    return {
        ...ContentFileFromJSONTyped(json, ignoreDiscriminator),
        'content': json['content'],
    };
}

export function PositionDeleteFileToJSON(value?: PositionDeleteFile | null): any {
    if (value == null) {
        return value;
    }
    return {
        ...ContentFileToJSON(value),
        'content': value['content'],
    };
}

