/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type PrimitiveTypeValue
 * 
 * @export
 */
export type PrimitiveTypeValue = Date | boolean | number | string;

export function PrimitiveTypeValueFromJSON(json: any): PrimitiveTypeValue {
    return PrimitiveTypeValueFromJSONTyped(json, false);
}

export function PrimitiveTypeValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrimitiveTypeValue {
    if (json == null) {
        return json;
    }
    return DateFromJSONTyped(json, true) || booleanFromJSONTyped(json, true) || numberFromJSONTyped(json, true) || stringFromJSONTyped(json, true);
}

export function PrimitiveTypeValueToJSON(value?: PrimitiveTypeValue | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfDate(value)) {
        return DateToJSON(value as Date);
    }
    if (instanceOfboolean(value)) {
        return booleanToJSON(value as boolean);
    }
    if (instanceOfnumber(value)) {
        return numberToJSON(value as number);
    }
    if (instanceOfstring(value)) {
        return stringToJSON(value as string);
    }

    return {};
}

