/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseUpdate } from './BaseUpdate';
import {
    BaseUpdateFromJSON,
    BaseUpdateFromJSONTyped,
    BaseUpdateToJSON,
    BaseUpdateToJSONTyped,
} from './BaseUpdate';

/**
 * 
 * @export
 * @interface RemovePartitionStatisticsUpdate
 */
export interface RemovePartitionStatisticsUpdate extends BaseUpdate {
    /**
     * 
     * @type {string}
     * @memberof RemovePartitionStatisticsUpdate
     */
    action: string;
    /**
     * 
     * @type {number}
     * @memberof RemovePartitionStatisticsUpdate
     */
    snapshotId: number;
}

/**
 * Check if a given object implements the RemovePartitionStatisticsUpdate interface.
 */
export function instanceOfRemovePartitionStatisticsUpdate(value: object): value is RemovePartitionStatisticsUpdate {
    if (!('snapshotId' in value) || value['snapshotId'] === undefined) return false;
    return true;
}

export function RemovePartitionStatisticsUpdateFromJSON(json: any): RemovePartitionStatisticsUpdate {
    return RemovePartitionStatisticsUpdateFromJSONTyped(json, false);
}

export function RemovePartitionStatisticsUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): RemovePartitionStatisticsUpdate {
    if (json == null) {
        return json;
    }
    return {
        ...BaseUpdateFromJSONTyped(json, true),
        'action': json['action'] == null ? undefined : json['action'],
        'snapshotId': json['snapshot-id'],
    };
}

export function RemovePartitionStatisticsUpdateToJSON(json: any): RemovePartitionStatisticsUpdate {
    return RemovePartitionStatisticsUpdateToJSONTyped(json, false);
}

export function RemovePartitionStatisticsUpdateToJSONTyped(value?: RemovePartitionStatisticsUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...BaseUpdateToJSONTyped(value, true),
        'action': value['action'],
        'snapshot-id': value['snapshotId'],
    };
}

