/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseUpdate } from './BaseUpdate';
import {
    BaseUpdateFromJSON,
    BaseUpdateFromJSONTyped,
    BaseUpdateToJSON,
} from './BaseUpdate';

/**
 * 
 * @export
 * @interface RemoveSnapshotRefUpdate
 */
export interface RemoveSnapshotRefUpdate extends BaseUpdate {
    /**
     * 
     * @type {string}
     * @memberof RemoveSnapshotRefUpdate
     */
    action: RemoveSnapshotRefUpdateActionEnum;
    /**
     * 
     * @type {string}
     * @memberof RemoveSnapshotRefUpdate
     */
    refName: string;
}


/**
 * @export
 */
export const RemoveSnapshotRefUpdateActionEnum = {
    RemoveSnapshotRef: 'remove-snapshot-ref'
} as const;
export type RemoveSnapshotRefUpdateActionEnum = typeof RemoveSnapshotRefUpdateActionEnum[keyof typeof RemoveSnapshotRefUpdateActionEnum];


/**
 * Check if a given object implements the RemoveSnapshotRefUpdate interface.
 */
export function instanceOfRemoveSnapshotRefUpdate(value: object): boolean {
    if (!('action' in value)) return false;
    if (!('refName' in value)) return false;
    return true;
}

export function RemoveSnapshotRefUpdateFromJSON(json: any): RemoveSnapshotRefUpdate {
    return RemoveSnapshotRefUpdateFromJSONTyped(json, false);
}

export function RemoveSnapshotRefUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): RemoveSnapshotRefUpdate {
    if (json == null) {
        return json;
    }
    return {
        ...BaseUpdateFromJSONTyped(json, ignoreDiscriminator),
        'action': json['action'],
        'refName': json['ref-name'],
    };
}

export function RemoveSnapshotRefUpdateToJSON(value?: RemoveSnapshotRefUpdate | null): any {
    if (value == null) {
        return value;
    }
    return {
        ...BaseUpdateToJSON(value),
        'action': value['action'],
        'ref-name': value['refName'],
    };
}

