/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseUpdate } from './BaseUpdate';
import {
    BaseUpdateFromJSON,
    BaseUpdateFromJSONTyped,
    BaseUpdateToJSON,
} from './BaseUpdate';

/**
 * 
 * @export
 * @interface RemovePropertiesUpdate
 */
export interface RemovePropertiesUpdate extends BaseUpdate {
    /**
     * 
     * @type {string}
     * @memberof RemovePropertiesUpdate
     */
    action: RemovePropertiesUpdateActionEnum;
    /**
     * 
     * @type {Array<string>}
     * @memberof RemovePropertiesUpdate
     */
    removals: Array<string>;
}


/**
 * @export
 */
export const RemovePropertiesUpdateActionEnum = {
    RemoveProperties: 'remove-properties'
} as const;
export type RemovePropertiesUpdateActionEnum = typeof RemovePropertiesUpdateActionEnum[keyof typeof RemovePropertiesUpdateActionEnum];


/**
 * Check if a given object implements the RemovePropertiesUpdate interface.
 */
export function instanceOfRemovePropertiesUpdate(value: object): boolean {
    if (!('action' in value)) return false;
    if (!('removals' in value)) return false;
    return true;
}

export function RemovePropertiesUpdateFromJSON(json: any): RemovePropertiesUpdate {
    return RemovePropertiesUpdateFromJSONTyped(json, false);
}

export function RemovePropertiesUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): RemovePropertiesUpdate {
    if (json == null) {
        return json;
    }
    return {
        ...BaseUpdateFromJSONTyped(json, ignoreDiscriminator),
        'action': json['action'],
        'removals': json['removals'],
    };
}

export function RemovePropertiesUpdateToJSON(value?: RemovePropertiesUpdate | null): any {
    if (value == null) {
        return value;
    }
    return {
        ...BaseUpdateToJSON(value),
        'action': value['action'],
        'removals': value['removals'],
    };
}

