/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseUpdate } from './BaseUpdate';
import {
    BaseUpdateFromJSON,
    BaseUpdateFromJSONTyped,
    BaseUpdateToJSON,
} from './BaseUpdate';

/**
 * 
 * @export
 * @interface RemoveSnapshotsUpdate
 */
export interface RemoveSnapshotsUpdate extends BaseUpdate {
    /**
     * 
     * @type {string}
     * @memberof RemoveSnapshotsUpdate
     */
    action: RemoveSnapshotsUpdateActionEnum;
    /**
     * 
     * @type {Array<number>}
     * @memberof RemoveSnapshotsUpdate
     */
    snapshotIds: Array<number>;
}


/**
 * @export
 */
export const RemoveSnapshotsUpdateActionEnum = {
    RemoveSnapshots: 'remove-snapshots'
} as const;
export type RemoveSnapshotsUpdateActionEnum = typeof RemoveSnapshotsUpdateActionEnum[keyof typeof RemoveSnapshotsUpdateActionEnum];


/**
 * Check if a given object implements the RemoveSnapshotsUpdate interface.
 */
export function instanceOfRemoveSnapshotsUpdate(value: object): boolean {
    if (!('action' in value)) return false;
    if (!('snapshotIds' in value)) return false;
    return true;
}

export function RemoveSnapshotsUpdateFromJSON(json: any): RemoveSnapshotsUpdate {
    return RemoveSnapshotsUpdateFromJSONTyped(json, false);
}

export function RemoveSnapshotsUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): RemoveSnapshotsUpdate {
    if (json == null) {
        return json;
    }
    return {
        ...BaseUpdateFromJSONTyped(json, ignoreDiscriminator),
        'action': json['action'],
        'snapshotIds': json['snapshot-ids'],
    };
}

export function RemoveSnapshotsUpdateToJSON(value?: RemoveSnapshotsUpdate | null): any {
    if (value == null) {
        return value;
    }
    return {
        ...BaseUpdateToJSON(value),
        'action': value['action'],
        'snapshot-ids': value['snapshotIds'],
    };
}

