/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseUpdate } from './BaseUpdate';
import {
    BaseUpdateFromJSON,
    BaseUpdateFromJSONTyped,
    BaseUpdateToJSON,
    BaseUpdateToJSONTyped,
} from './BaseUpdate';

/**
 * 
 * @export
 * @interface RemoveSnapshotsUpdate
 */
export interface RemoveSnapshotsUpdate extends BaseUpdate {
    /**
     * 
     * @type {string}
     * @memberof RemoveSnapshotsUpdate
     */
    action: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof RemoveSnapshotsUpdate
     */
    snapshotIds: Array<number>;
}

/**
 * Check if a given object implements the RemoveSnapshotsUpdate interface.
 */
export function instanceOfRemoveSnapshotsUpdate(value: object): value is RemoveSnapshotsUpdate {
    if (!('snapshotIds' in value) || value['snapshotIds'] === undefined) return false;
    return true;
}

export function RemoveSnapshotsUpdateFromJSON(json: any): RemoveSnapshotsUpdate {
    return RemoveSnapshotsUpdateFromJSONTyped(json, false);
}

export function RemoveSnapshotsUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): RemoveSnapshotsUpdate {
    if (json == null) {
        return json;
    }
    return {
        ...BaseUpdateFromJSONTyped(json, true),
        'action': json['action'] == null ? undefined : json['action'],
        'snapshotIds': json['snapshot-ids'],
    };
}

export function RemoveSnapshotsUpdateToJSON(json: any): RemoveSnapshotsUpdate {
    return RemoveSnapshotsUpdateToJSONTyped(json, false);
}

export function RemoveSnapshotsUpdateToJSONTyped(value?: RemoveSnapshotsUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...BaseUpdateToJSONTyped(value, true),
        'action': value['action'],
        'snapshot-ids': value['snapshotIds'],
    };
}

