/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseUpdate } from './BaseUpdate';
import {
    BaseUpdateFromJSON,
    BaseUpdateFromJSONTyped,
    BaseUpdateToJSON,
    BaseUpdateToJSONTyped,
} from './BaseUpdate';

/**
 * 
 * @export
 * @interface RemovePropertiesUpdate
 */
export interface RemovePropertiesUpdate extends BaseUpdate {
    /**
     * 
     * @type {string}
     * @memberof RemovePropertiesUpdate
     */
    action: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof RemovePropertiesUpdate
     */
    removals: Array<string>;
}

/**
 * Check if a given object implements the RemovePropertiesUpdate interface.
 */
export function instanceOfRemovePropertiesUpdate(value: object): value is RemovePropertiesUpdate {
    if (!('removals' in value) || value['removals'] === undefined) return false;
    return true;
}

export function RemovePropertiesUpdateFromJSON(json: any): RemovePropertiesUpdate {
    return RemovePropertiesUpdateFromJSONTyped(json, false);
}

export function RemovePropertiesUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): RemovePropertiesUpdate {
    if (json == null) {
        return json;
    }
    return {
        ...BaseUpdateFromJSONTyped(json, true),
        'action': json['action'] == null ? undefined : json['action'],
        'removals': json['removals'],
    };
}

export function RemovePropertiesUpdateToJSON(json: any): RemovePropertiesUpdate {
    return RemovePropertiesUpdateToJSONTyped(json, false);
}

export function RemovePropertiesUpdateToJSONTyped(value?: RemovePropertiesUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...BaseUpdateToJSONTyped(value, true),
        'action': value['action'],
        'removals': value['removals'],
    };
}

