/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommitReport } from './CommitReport';
import {
    CommitReportFromJSON,
    CommitReportFromJSONTyped,
    CommitReportToJSON,
    CommitReportToJSONTyped,
} from './CommitReport';
import type { Expression } from './Expression';
import {
    ExpressionFromJSON,
    ExpressionFromJSONTyped,
    ExpressionToJSON,
    ExpressionToJSONTyped,
} from './Expression';
import type { ScanReport } from './ScanReport';
import {
    ScanReportFromJSON,
    ScanReportFromJSONTyped,
    ScanReportToJSON,
    ScanReportToJSONTyped,
} from './ScanReport';
import type { MetricResult } from './MetricResult';
import {
    MetricResultFromJSON,
    MetricResultFromJSONTyped,
    MetricResultToJSON,
    MetricResultToJSONTyped,
} from './MetricResult';

/**
 * 
 * @export
 * @interface ReportMetricsRequest
 */
export interface ReportMetricsRequest {
    /**
     * 
     * @type {string}
     * @memberof ReportMetricsRequest
     */
    reportType: string;
    /**
     * 
     * @type {string}
     * @memberof ReportMetricsRequest
     */
    tableName: string;
    /**
     * 
     * @type {number}
     * @memberof ReportMetricsRequest
     */
    snapshotId: number;
    /**
     * 
     * @type {Expression}
     * @memberof ReportMetricsRequest
     */
    filter: Expression;
    /**
     * 
     * @type {number}
     * @memberof ReportMetricsRequest
     */
    schemaId: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof ReportMetricsRequest
     */
    projectedFieldIds: Array<number>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ReportMetricsRequest
     */
    projectedFieldNames: Array<string>;
    /**
     * 
     * @type {{ [key: string]: MetricResult; }}
     * @memberof ReportMetricsRequest
     */
    metrics: { [key: string]: MetricResult; };
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ReportMetricsRequest
     */
    metadata?: { [key: string]: string; };
    /**
     * 
     * @type {number}
     * @memberof ReportMetricsRequest
     */
    sequenceNumber: number;
    /**
     * 
     * @type {string}
     * @memberof ReportMetricsRequest
     */
    operation: string;
}

/**
 * Check if a given object implements the ReportMetricsRequest interface.
 */
export function instanceOfReportMetricsRequest(value: object): value is ReportMetricsRequest {
    if (!('reportType' in value) || value['reportType'] === undefined) return false;
    if (!('tableName' in value) || value['tableName'] === undefined) return false;
    if (!('snapshotId' in value) || value['snapshotId'] === undefined) return false;
    if (!('filter' in value) || value['filter'] === undefined) return false;
    if (!('schemaId' in value) || value['schemaId'] === undefined) return false;
    if (!('projectedFieldIds' in value) || value['projectedFieldIds'] === undefined) return false;
    if (!('projectedFieldNames' in value) || value['projectedFieldNames'] === undefined) return false;
    if (!('metrics' in value) || value['metrics'] === undefined) return false;
    if (!('sequenceNumber' in value) || value['sequenceNumber'] === undefined) return false;
    if (!('operation' in value) || value['operation'] === undefined) return false;
    return true;
}

export function ReportMetricsRequestFromJSON(json: any): ReportMetricsRequest {
    return ReportMetricsRequestFromJSONTyped(json, false);
}

export function ReportMetricsRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReportMetricsRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'reportType': json['report-type'],
        'tableName': json['table-name'],
        'snapshotId': json['snapshot-id'],
        'filter': ExpressionFromJSON(json['filter']),
        'schemaId': json['schema-id'],
        'projectedFieldIds': json['projected-field-ids'],
        'projectedFieldNames': json['projected-field-names'],
        'metrics': (mapValues(json['metrics'], MetricResultFromJSON)),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
        'sequenceNumber': json['sequence-number'],
        'operation': json['operation'],
    };
}

export function ReportMetricsRequestToJSON(json: any): ReportMetricsRequest {
    return ReportMetricsRequestToJSONTyped(json, false);
}

export function ReportMetricsRequestToJSONTyped(value?: ReportMetricsRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'report-type': value['reportType'],
        'table-name': value['tableName'],
        'snapshot-id': value['snapshotId'],
        'filter': ExpressionToJSON(value['filter']),
        'schema-id': value['schemaId'],
        'projected-field-ids': value['projectedFieldIds'],
        'projected-field-names': value['projectedFieldNames'],
        'metrics': (mapValues(value['metrics'], MetricResultToJSON)),
        'metadata': value['metadata'],
        'sequence-number': value['sequenceNumber'],
        'operation': value['operation'],
    };
}

