/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Expression } from './Expression';
import {
    ExpressionFromJSON,
    ExpressionFromJSONTyped,
    ExpressionToJSON,
    ExpressionToJSONTyped,
} from './Expression';
import type { MetricResult } from './MetricResult';
import {
    MetricResultFromJSON,
    MetricResultFromJSONTyped,
    MetricResultToJSON,
    MetricResultToJSONTyped,
} from './MetricResult';

/**
 * 
 * @export
 * @interface ScanReport
 */
export interface ScanReport {
    /**
     * 
     * @type {string}
     * @memberof ScanReport
     */
    tableName: string;
    /**
     * 
     * @type {number}
     * @memberof ScanReport
     */
    snapshotId: number;
    /**
     * 
     * @type {Expression}
     * @memberof ScanReport
     */
    filter: Expression;
    /**
     * 
     * @type {number}
     * @memberof ScanReport
     */
    schemaId: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof ScanReport
     */
    projectedFieldIds: Array<number>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ScanReport
     */
    projectedFieldNames: Array<string>;
    /**
     * 
     * @type {{ [key: string]: MetricResult; }}
     * @memberof ScanReport
     */
    metrics: { [key: string]: MetricResult; };
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ScanReport
     */
    metadata?: { [key: string]: string; };
}

/**
 * Check if a given object implements the ScanReport interface.
 */
export function instanceOfScanReport(value: object): value is ScanReport {
    if (!('tableName' in value) || value['tableName'] === undefined) return false;
    if (!('snapshotId' in value) || value['snapshotId'] === undefined) return false;
    if (!('filter' in value) || value['filter'] === undefined) return false;
    if (!('schemaId' in value) || value['schemaId'] === undefined) return false;
    if (!('projectedFieldIds' in value) || value['projectedFieldIds'] === undefined) return false;
    if (!('projectedFieldNames' in value) || value['projectedFieldNames'] === undefined) return false;
    if (!('metrics' in value) || value['metrics'] === undefined) return false;
    return true;
}

export function ScanReportFromJSON(json: any): ScanReport {
    return ScanReportFromJSONTyped(json, false);
}

export function ScanReportFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScanReport {
    if (json == null) {
        return json;
    }
    return {
        
        'tableName': json['table-name'],
        'snapshotId': json['snapshot-id'],
        'filter': ExpressionFromJSON(json['filter']),
        'schemaId': json['schema-id'],
        'projectedFieldIds': json['projected-field-ids'],
        'projectedFieldNames': json['projected-field-names'],
        'metrics': (mapValues(json['metrics'], MetricResultFromJSON)),
        'metadata': json['metadata'] == null ? undefined : json['metadata'],
    };
}

export function ScanReportToJSON(json: any): ScanReport {
    return ScanReportToJSONTyped(json, false);
}

export function ScanReportToJSONTyped(value?: ScanReport | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'table-name': value['tableName'],
        'snapshot-id': value['snapshotId'],
        'filter': ExpressionToJSON(value['filter']),
        'schema-id': value['schemaId'],
        'projected-field-ids': value['projectedFieldIds'],
        'projected-field-names': value['projectedFieldNames'],
        'metrics': (mapValues(value['metrics'], MetricResultToJSON)),
        'metadata': value['metadata'],
    };
}

