/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseUpdate } from './BaseUpdate';
import {
    BaseUpdateFromJSON,
    BaseUpdateFromJSONTyped,
    BaseUpdateToJSON,
    BaseUpdateToJSONTyped,
} from './BaseUpdate';

/**
 * 
 * @export
 * @interface SetCurrentViewVersionUpdate
 */
export interface SetCurrentViewVersionUpdate extends BaseUpdate {
    /**
     * 
     * @type {string}
     * @memberof SetCurrentViewVersionUpdate
     */
    action: string;
    /**
     * The view version id to set as current, or -1 to set last added view version id
     * @type {number}
     * @memberof SetCurrentViewVersionUpdate
     */
    viewVersionId: number;
}

/**
 * Check if a given object implements the SetCurrentViewVersionUpdate interface.
 */
export function instanceOfSetCurrentViewVersionUpdate(value: object): value is SetCurrentViewVersionUpdate {
    if (!('viewVersionId' in value) || value['viewVersionId'] === undefined) return false;
    return true;
}

export function SetCurrentViewVersionUpdateFromJSON(json: any): SetCurrentViewVersionUpdate {
    return SetCurrentViewVersionUpdateFromJSONTyped(json, false);
}

export function SetCurrentViewVersionUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetCurrentViewVersionUpdate {
    if (json == null) {
        return json;
    }
    return {
        ...BaseUpdateFromJSONTyped(json, true),
        'action': json['action'] == null ? undefined : json['action'],
        'viewVersionId': json['view-version-id'],
    };
}

export function SetCurrentViewVersionUpdateToJSON(json: any): SetCurrentViewVersionUpdate {
    return SetCurrentViewVersionUpdateToJSONTyped(json, false);
}

export function SetCurrentViewVersionUpdateToJSONTyped(value?: SetCurrentViewVersionUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...BaseUpdateToJSONTyped(value, true),
        'action': value['action'],
        'view-version-id': value['viewVersionId'],
    };
}

