/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseUpdate } from './BaseUpdate';
import {
    BaseUpdateFromJSON,
    BaseUpdateFromJSONTyped,
    BaseUpdateToJSON,
    BaseUpdateToJSONTyped,
} from './BaseUpdate';

/**
 * 
 * @export
 * @interface SetCurrentSchemaUpdate
 */
export interface SetCurrentSchemaUpdate extends BaseUpdate {
    /**
     * 
     * @type {string}
     * @memberof SetCurrentSchemaUpdate
     */
    action: string;
    /**
     * Schema ID to set as current, or -1 to set last added schema
     * @type {number}
     * @memberof SetCurrentSchemaUpdate
     */
    schemaId: number;
}

/**
 * Check if a given object implements the SetCurrentSchemaUpdate interface.
 */
export function instanceOfSetCurrentSchemaUpdate(value: object): value is SetCurrentSchemaUpdate {
    if (!('schemaId' in value) || value['schemaId'] === undefined) return false;
    return true;
}

export function SetCurrentSchemaUpdateFromJSON(json: any): SetCurrentSchemaUpdate {
    return SetCurrentSchemaUpdateFromJSONTyped(json, false);
}

export function SetCurrentSchemaUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetCurrentSchemaUpdate {
    if (json == null) {
        return json;
    }
    return {
        ...BaseUpdateFromJSONTyped(json, true),
        'action': json['action'] == null ? undefined : json['action'],
        'schemaId': json['schema-id'],
    };
}

export function SetCurrentSchemaUpdateToJSON(json: any): SetCurrentSchemaUpdate {
    return SetCurrentSchemaUpdateToJSONTyped(json, false);
}

export function SetCurrentSchemaUpdateToJSONTyped(value?: SetCurrentSchemaUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...BaseUpdateToJSONTyped(value, true),
        'action': value['action'],
        'schema-id': value['schemaId'],
    };
}

