/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseUpdate } from './BaseUpdate';
import {
    BaseUpdateFromJSON,
    BaseUpdateFromJSONTyped,
    BaseUpdateToJSON,
} from './BaseUpdate';

/**
 * 
 * @export
 * @interface SetCurrentViewVersionUpdate
 */
export interface SetCurrentViewVersionUpdate extends BaseUpdate {
    /**
     * 
     * @type {string}
     * @memberof SetCurrentViewVersionUpdate
     */
    action: SetCurrentViewVersionUpdateActionEnum;
    /**
     * The view version id to set as current, or -1 to set last added view version id
     * @type {number}
     * @memberof SetCurrentViewVersionUpdate
     */
    viewVersionId: number;
}


/**
 * @export
 */
export const SetCurrentViewVersionUpdateActionEnum = {
    SetCurrentViewVersion: 'set-current-view-version'
} as const;
export type SetCurrentViewVersionUpdateActionEnum = typeof SetCurrentViewVersionUpdateActionEnum[keyof typeof SetCurrentViewVersionUpdateActionEnum];


/**
 * Check if a given object implements the SetCurrentViewVersionUpdate interface.
 */
export function instanceOfSetCurrentViewVersionUpdate(value: object): boolean {
    if (!('action' in value)) return false;
    if (!('viewVersionId' in value)) return false;
    return true;
}

export function SetCurrentViewVersionUpdateFromJSON(json: any): SetCurrentViewVersionUpdate {
    return SetCurrentViewVersionUpdateFromJSONTyped(json, false);
}

export function SetCurrentViewVersionUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetCurrentViewVersionUpdate {
    if (json == null) {
        return json;
    }
    return {
        ...BaseUpdateFromJSONTyped(json, ignoreDiscriminator),
        'action': json['action'],
        'viewVersionId': json['view-version-id'],
    };
}

export function SetCurrentViewVersionUpdateToJSON(value?: SetCurrentViewVersionUpdate | null): any {
    if (value == null) {
        return value;
    }
    return {
        ...BaseUpdateToJSON(value),
        'action': value['action'],
        'view-version-id': value['viewVersionId'],
    };
}

