/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseUpdate } from './BaseUpdate';
import {
    BaseUpdateFromJSON,
    BaseUpdateFromJSONTyped,
    BaseUpdateToJSON,
    BaseUpdateToJSONTyped,
} from './BaseUpdate';

/**
 * 
 * @export
 * @interface SetDefaultSortOrderUpdate
 */
export interface SetDefaultSortOrderUpdate extends BaseUpdate {
    /**
     * 
     * @type {string}
     * @memberof SetDefaultSortOrderUpdate
     */
    action: string;
    /**
     * Sort order ID to set as the default, or -1 to set last added sort order
     * @type {number}
     * @memberof SetDefaultSortOrderUpdate
     */
    sortOrderId: number;
}

/**
 * Check if a given object implements the SetDefaultSortOrderUpdate interface.
 */
export function instanceOfSetDefaultSortOrderUpdate(value: object): value is SetDefaultSortOrderUpdate {
    if (!('sortOrderId' in value) || value['sortOrderId'] === undefined) return false;
    return true;
}

export function SetDefaultSortOrderUpdateFromJSON(json: any): SetDefaultSortOrderUpdate {
    return SetDefaultSortOrderUpdateFromJSONTyped(json, false);
}

export function SetDefaultSortOrderUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetDefaultSortOrderUpdate {
    if (json == null) {
        return json;
    }
    return {
        ...BaseUpdateFromJSONTyped(json, true),
        'action': json['action'] == null ? undefined : json['action'],
        'sortOrderId': json['sort-order-id'],
    };
}

export function SetDefaultSortOrderUpdateToJSON(json: any): SetDefaultSortOrderUpdate {
    return SetDefaultSortOrderUpdateToJSONTyped(json, false);
}

export function SetDefaultSortOrderUpdateToJSONTyped(value?: SetDefaultSortOrderUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...BaseUpdateToJSONTyped(value, true),
        'action': value['action'],
        'sort-order-id': value['sortOrderId'],
    };
}

