/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseUpdate } from './BaseUpdate';
import {
    BaseUpdateFromJSON,
    BaseUpdateFromJSONTyped,
    BaseUpdateToJSON,
} from './BaseUpdate';

/**
 * 
 * @export
 * @interface SetLocationUpdate
 */
export interface SetLocationUpdate extends BaseUpdate {
    /**
     * 
     * @type {string}
     * @memberof SetLocationUpdate
     */
    action: SetLocationUpdateActionEnum;
    /**
     * 
     * @type {string}
     * @memberof SetLocationUpdate
     */
    location: string;
}


/**
 * @export
 */
export const SetLocationUpdateActionEnum = {
    SetLocation: 'set-location'
} as const;
export type SetLocationUpdateActionEnum = typeof SetLocationUpdateActionEnum[keyof typeof SetLocationUpdateActionEnum];


/**
 * Check if a given object implements the SetLocationUpdate interface.
 */
export function instanceOfSetLocationUpdate(value: object): boolean {
    if (!('action' in value)) return false;
    if (!('location' in value)) return false;
    return true;
}

export function SetLocationUpdateFromJSON(json: any): SetLocationUpdate {
    return SetLocationUpdateFromJSONTyped(json, false);
}

export function SetLocationUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetLocationUpdate {
    if (json == null) {
        return json;
    }
    return {
        ...BaseUpdateFromJSONTyped(json, ignoreDiscriminator),
        'action': json['action'],
        'location': json['location'],
    };
}

export function SetLocationUpdateToJSON(value?: SetLocationUpdate | null): any {
    if (value == null) {
        return value;
    }
    return {
        ...BaseUpdateToJSON(value),
        'action': value['action'],
        'location': value['location'],
    };
}

