/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseUpdate } from './BaseUpdate';
import {
    BaseUpdateFromJSON,
    BaseUpdateFromJSONTyped,
    BaseUpdateToJSON,
} from './BaseUpdate';
import type { PartitionStatisticsFile } from './PartitionStatisticsFile';
import {
    PartitionStatisticsFileFromJSON,
    PartitionStatisticsFileFromJSONTyped,
    PartitionStatisticsFileToJSON,
} from './PartitionStatisticsFile';

/**
 * 
 * @export
 * @interface SetPartitionStatisticsUpdate
 */
export interface SetPartitionStatisticsUpdate extends BaseUpdate {
    /**
     * 
     * @type {string}
     * @memberof SetPartitionStatisticsUpdate
     */
    action: SetPartitionStatisticsUpdateActionEnum;
    /**
     * 
     * @type {PartitionStatisticsFile}
     * @memberof SetPartitionStatisticsUpdate
     */
    partitionStatistics: PartitionStatisticsFile;
}


/**
 * @export
 */
export const SetPartitionStatisticsUpdateActionEnum = {
    SetPartitionStatistics: 'set-partition-statistics'
} as const;
export type SetPartitionStatisticsUpdateActionEnum = typeof SetPartitionStatisticsUpdateActionEnum[keyof typeof SetPartitionStatisticsUpdateActionEnum];


/**
 * Check if a given object implements the SetPartitionStatisticsUpdate interface.
 */
export function instanceOfSetPartitionStatisticsUpdate(value: object): boolean {
    if (!('action' in value)) return false;
    if (!('partitionStatistics' in value)) return false;
    return true;
}

export function SetPartitionStatisticsUpdateFromJSON(json: any): SetPartitionStatisticsUpdate {
    return SetPartitionStatisticsUpdateFromJSONTyped(json, false);
}

export function SetPartitionStatisticsUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetPartitionStatisticsUpdate {
    if (json == null) {
        return json;
    }
    return {
        ...BaseUpdateFromJSONTyped(json, ignoreDiscriminator),
        'action': json['action'],
        'partitionStatistics': PartitionStatisticsFileFromJSON(json['partition-statistics']),
    };
}

export function SetPartitionStatisticsUpdateToJSON(value?: SetPartitionStatisticsUpdate | null): any {
    if (value == null) {
        return value;
    }
    return {
        ...BaseUpdateToJSON(value),
        'action': value['action'],
        'partition-statistics': PartitionStatisticsFileToJSON(value['partitionStatistics']),
    };
}

