/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseUpdate } from './BaseUpdate';
import {
    BaseUpdateFromJSON,
    BaseUpdateFromJSONTyped,
    BaseUpdateToJSON,
    BaseUpdateToJSONTyped,
} from './BaseUpdate';
import type { PartitionStatisticsFile } from './PartitionStatisticsFile';
import {
    PartitionStatisticsFileFromJSON,
    PartitionStatisticsFileFromJSONTyped,
    PartitionStatisticsFileToJSON,
    PartitionStatisticsFileToJSONTyped,
} from './PartitionStatisticsFile';

/**
 * 
 * @export
 * @interface SetPartitionStatisticsUpdate
 */
export interface SetPartitionStatisticsUpdate extends BaseUpdate {
    /**
     * 
     * @type {string}
     * @memberof SetPartitionStatisticsUpdate
     */
    action: string;
    /**
     * 
     * @type {PartitionStatisticsFile}
     * @memberof SetPartitionStatisticsUpdate
     */
    partitionStatistics: PartitionStatisticsFile;
}

/**
 * Check if a given object implements the SetPartitionStatisticsUpdate interface.
 */
export function instanceOfSetPartitionStatisticsUpdate(value: object): value is SetPartitionStatisticsUpdate {
    if (!('partitionStatistics' in value) || value['partitionStatistics'] === undefined) return false;
    return true;
}

export function SetPartitionStatisticsUpdateFromJSON(json: any): SetPartitionStatisticsUpdate {
    return SetPartitionStatisticsUpdateFromJSONTyped(json, false);
}

export function SetPartitionStatisticsUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetPartitionStatisticsUpdate {
    if (json == null) {
        return json;
    }
    return {
        ...BaseUpdateFromJSONTyped(json, true),
        'action': json['action'] == null ? undefined : json['action'],
        'partitionStatistics': PartitionStatisticsFileFromJSON(json['partition-statistics']),
    };
}

export function SetPartitionStatisticsUpdateToJSON(json: any): SetPartitionStatisticsUpdate {
    return SetPartitionStatisticsUpdateToJSONTyped(json, false);
}

export function SetPartitionStatisticsUpdateToJSONTyped(value?: SetPartitionStatisticsUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...BaseUpdateToJSONTyped(value, true),
        'action': value['action'],
        'partition-statistics': PartitionStatisticsFileToJSON(value['partitionStatistics']),
    };
}

