/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseUpdate } from './BaseUpdate';
import {
    BaseUpdateFromJSON,
    BaseUpdateFromJSONTyped,
    BaseUpdateToJSON,
    BaseUpdateToJSONTyped,
} from './BaseUpdate';

/**
 * 
 * @export
 * @interface SetPropertiesUpdate
 */
export interface SetPropertiesUpdate extends BaseUpdate {
    /**
     * 
     * @type {string}
     * @memberof SetPropertiesUpdate
     */
    action: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof SetPropertiesUpdate
     */
    updates: { [key: string]: string; };
}

/**
 * Check if a given object implements the SetPropertiesUpdate interface.
 */
export function instanceOfSetPropertiesUpdate(value: object): value is SetPropertiesUpdate {
    if (!('updates' in value) || value['updates'] === undefined) return false;
    return true;
}

export function SetPropertiesUpdateFromJSON(json: any): SetPropertiesUpdate {
    return SetPropertiesUpdateFromJSONTyped(json, false);
}

export function SetPropertiesUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetPropertiesUpdate {
    if (json == null) {
        return json;
    }
    return {
        ...BaseUpdateFromJSONTyped(json, true),
        'action': json['action'] == null ? undefined : json['action'],
        'updates': json['updates'],
    };
}

export function SetPropertiesUpdateToJSON(json: any): SetPropertiesUpdate {
    return SetPropertiesUpdateToJSONTyped(json, false);
}

export function SetPropertiesUpdateToJSONTyped(value?: SetPropertiesUpdate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...BaseUpdateToJSONTyped(value, true),
        'action': value['action'],
        'updates': value['updates'],
    };
}

