/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseUpdate } from './BaseUpdate';
import {
    BaseUpdateFromJSON,
    BaseUpdateFromJSONTyped,
    BaseUpdateToJSON,
} from './BaseUpdate';
import type { StatisticsFile } from './StatisticsFile';
import {
    StatisticsFileFromJSON,
    StatisticsFileFromJSONTyped,
    StatisticsFileToJSON,
} from './StatisticsFile';

/**
 * 
 * @export
 * @interface SetStatisticsUpdate
 */
export interface SetStatisticsUpdate extends BaseUpdate {
    /**
     * 
     * @type {string}
     * @memberof SetStatisticsUpdate
     */
    action: SetStatisticsUpdateActionEnum;
    /**
     * 
     * @type {number}
     * @memberof SetStatisticsUpdate
     */
    snapshotId: number;
    /**
     * 
     * @type {StatisticsFile}
     * @memberof SetStatisticsUpdate
     */
    statistics: StatisticsFile;
}


/**
 * @export
 */
export const SetStatisticsUpdateActionEnum = {
    SetStatistics: 'set-statistics'
} as const;
export type SetStatisticsUpdateActionEnum = typeof SetStatisticsUpdateActionEnum[keyof typeof SetStatisticsUpdateActionEnum];


/**
 * Check if a given object implements the SetStatisticsUpdate interface.
 */
export function instanceOfSetStatisticsUpdate(value: object): boolean {
    if (!('action' in value)) return false;
    if (!('snapshotId' in value)) return false;
    if (!('statistics' in value)) return false;
    return true;
}

export function SetStatisticsUpdateFromJSON(json: any): SetStatisticsUpdate {
    return SetStatisticsUpdateFromJSONTyped(json, false);
}

export function SetStatisticsUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetStatisticsUpdate {
    if (json == null) {
        return json;
    }
    return {
        ...BaseUpdateFromJSONTyped(json, ignoreDiscriminator),
        'action': json['action'],
        'snapshotId': json['snapshot-id'],
        'statistics': StatisticsFileFromJSON(json['statistics']),
    };
}

export function SetStatisticsUpdateToJSON(value?: SetStatisticsUpdate | null): any {
    if (value == null) {
        return value;
    }
    return {
        ...BaseUpdateToJSON(value),
        'action': value['action'],
        'snapshot-id': value['snapshotId'],
        'statistics': StatisticsFileToJSON(value['statistics']),
    };
}

