/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SnapshotLogInner
 */
export interface SnapshotLogInner {
    /**
     * 
     * @type {number}
     * @memberof SnapshotLogInner
     */
    snapshotId: number;
    /**
     * 
     * @type {number}
     * @memberof SnapshotLogInner
     */
    timestampMs: number;
}

/**
 * Check if a given object implements the SnapshotLogInner interface.
 */
export function instanceOfSnapshotLogInner(value: object): value is SnapshotLogInner {
    if (!('snapshotId' in value) || value['snapshotId'] === undefined) return false;
    if (!('timestampMs' in value) || value['timestampMs'] === undefined) return false;
    return true;
}

export function SnapshotLogInnerFromJSON(json: any): SnapshotLogInner {
    return SnapshotLogInnerFromJSONTyped(json, false);
}

export function SnapshotLogInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): SnapshotLogInner {
    if (json == null) {
        return json;
    }
    return {
        
        'snapshotId': json['snapshot-id'],
        'timestampMs': json['timestamp-ms'],
    };
}

export function SnapshotLogInnerToJSON(json: any): SnapshotLogInner {
    return SnapshotLogInnerToJSONTyped(json, false);
}

export function SnapshotLogInnerToJSONTyped(value?: SnapshotLogInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'snapshot-id': value['snapshotId'],
        'timestamp-ms': value['timestampMs'],
    };
}

