/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SnapshotSummary
 */
export interface SnapshotSummary {
    [key: string]: string | any;
    /**
     * 
     * @type {string}
     * @memberof SnapshotSummary
     */
    operation: SnapshotSummaryOperationEnum;
}


/**
 * @export
 */
export const SnapshotSummaryOperationEnum = {
    Append: 'append',
    Replace: 'replace',
    Overwrite: 'overwrite',
    Delete: 'delete'
} as const;
export type SnapshotSummaryOperationEnum = typeof SnapshotSummaryOperationEnum[keyof typeof SnapshotSummaryOperationEnum];


/**
 * Check if a given object implements the SnapshotSummary interface.
 */
export function instanceOfSnapshotSummary(value: object): value is SnapshotSummary {
    if (!('operation' in value) || value['operation'] === undefined) return false;
    return true;
}

export function SnapshotSummaryFromJSON(json: any): SnapshotSummary {
    return SnapshotSummaryFromJSONTyped(json, false);
}

export function SnapshotSummaryFromJSONTyped(json: any, ignoreDiscriminator: boolean): SnapshotSummary {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'operation': json['operation'],
    };
}

export function SnapshotSummaryToJSON(json: any): SnapshotSummary {
    return SnapshotSummaryToJSONTyped(json, false);
}

export function SnapshotSummaryToJSONTyped(value?: SnapshotSummary | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
            ...value,
        'operation': value['operation'],
    };
}

