/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StructField } from './StructField';
import {
    StructFieldFromJSON,
    StructFieldFromJSONTyped,
    StructFieldToJSON,
} from './StructField';

/**
 * 
 * @export
 * @interface StructType
 */
export interface StructType {
    /**
     * 
     * @type {string}
     * @memberof StructType
     */
    type: StructTypeTypeEnum;
    /**
     * 
     * @type {Array<StructField>}
     * @memberof StructType
     */
    fields: Array<StructField>;
}


/**
 * @export
 */
export const StructTypeTypeEnum = {
    Struct: 'struct'
} as const;
export type StructTypeTypeEnum = typeof StructTypeTypeEnum[keyof typeof StructTypeTypeEnum];


/**
 * Check if a given object implements the StructType interface.
 */
export function instanceOfStructType(value: object): boolean {
    if (!('type' in value)) return false;
    if (!('fields' in value)) return false;
    return true;
}

export function StructTypeFromJSON(json: any): StructType {
    return StructTypeFromJSONTyped(json, false);
}

export function StructTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): StructType {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'fields': ((json['fields'] as Array<any>).map(StructFieldFromJSON)),
    };
}

export function StructTypeToJSON(value?: StructType | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'type': value['type'],
        'fields': ((value['fields'] as Array<any>).map(StructFieldToJSON)),
    };
}

