/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Type } from './Type';
import {
    TypeFromJSON,
    TypeFromJSONTyped,
    TypeToJSON,
} from './Type';

/**
 * 
 * @export
 * @interface StructField
 */
export interface StructField {
    /**
     * 
     * @type {number}
     * @memberof StructField
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof StructField
     */
    name: string;
    /**
     * 
     * @type {Type}
     * @memberof StructField
     */
    type: Type;
    /**
     * 
     * @type {boolean}
     * @memberof StructField
     */
    required: boolean;
    /**
     * 
     * @type {string}
     * @memberof StructField
     */
    doc?: string;
}

/**
 * Check if a given object implements the StructField interface.
 */
export function instanceOfStructField(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('name' in value)) return false;
    if (!('type' in value)) return false;
    if (!('required' in value)) return false;
    return true;
}

export function StructFieldFromJSON(json: any): StructField {
    return StructFieldFromJSONTyped(json, false);
}

export function StructFieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): StructField {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'type': TypeFromJSON(json['type']),
        'required': json['required'],
        'doc': json['doc'] == null ? undefined : json['doc'],
    };
}

export function StructFieldToJSON(value?: StructField | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'type': TypeToJSON(value['type']),
        'required': value['required'],
        'doc': value['doc'],
    };
}

