/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TableIdentifier
 */
export interface TableIdentifier {
    /**
     * Reference to one or more levels of a namespace
     * @type {Array<string>}
     * @memberof TableIdentifier
     */
    namespace: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof TableIdentifier
     */
    name: string;
}

/**
 * Check if a given object implements the TableIdentifier interface.
 */
export function instanceOfTableIdentifier(value: object): value is TableIdentifier {
    if (!('namespace' in value) || value['namespace'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function TableIdentifierFromJSON(json: any): TableIdentifier {
    return TableIdentifierFromJSONTyped(json, false);
}

export function TableIdentifierFromJSONTyped(json: any, ignoreDiscriminator: boolean): TableIdentifier {
    if (json == null) {
        return json;
    }
    return {
        
        'namespace': json['namespace'],
        'name': json['name'],
    };
}

export function TableIdentifierToJSON(json: any): TableIdentifier {
    return TableIdentifierToJSONTyped(json, false);
}

export function TableIdentifierToJSONTyped(value?: TableIdentifier | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'namespace': value['namespace'],
        'name': value['name'],
    };
}

