/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { TransformTerm } from './TransformTerm';
import {
    instanceOfTransformTerm,
    TransformTermFromJSON,
    TransformTermFromJSONTyped,
    TransformTermToJSON,
} from './TransformTerm';

/**
 * @type Term
 * 
 * @export
 */
export type Term = TransformTerm | string;

export function TermFromJSON(json: any): Term {
    return TermFromJSONTyped(json, false);
}

export function TermFromJSONTyped(json: any, ignoreDiscriminator: boolean): Term {
    if (json == null) {
        return json;
    }
    if (instanceOfTransformTerm(json)) {
        return TransformTermFromJSONTyped(json, true);
    }
    if (typeof json === 'string') {
        return json;
    }

    return {} as any;
}

export function TermToJSON(json: any): any {
    return TermToJSONTyped(json, false);
}

export function TermToJSONTyped(value?: Term | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    if (instanceOfTransformTerm(value as object)) {
        return TransformTermToJSON(value as TransformTerm);
    }
    if (typeof value === 'string') {
        return value;
    }

    return {};
}

