/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TrueExpression
 */
export interface TrueExpression {
    /**
     * 
     * @type {string}
     * @memberof TrueExpression
     */
    type: string;
}

/**
 * Check if a given object implements the TrueExpression interface.
 */
export function instanceOfTrueExpression(value: object): value is TrueExpression {
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function TrueExpressionFromJSON(json: any): TrueExpression {
    return TrueExpressionFromJSONTyped(json, false);
}

export function TrueExpressionFromJSONTyped(json: any, ignoreDiscriminator: boolean): TrueExpression {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
    };
}

export function TrueExpressionToJSON(json: any): TrueExpression {
    return TrueExpressionToJSONTyped(json, false);
}

export function TrueExpressionToJSONTyped(value?: TrueExpression | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
    };
}

