/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BaseUpdate } from './BaseUpdate';
import {
    BaseUpdateFromJSON,
    BaseUpdateFromJSONTyped,
    BaseUpdateToJSON,
} from './BaseUpdate';

/**
 * 
 * @export
 * @interface UpgradeFormatVersionUpdate
 */
export interface UpgradeFormatVersionUpdate extends BaseUpdate {
    /**
     * 
     * @type {string}
     * @memberof UpgradeFormatVersionUpdate
     */
    action: UpgradeFormatVersionUpdateActionEnum;
    /**
     * 
     * @type {number}
     * @memberof UpgradeFormatVersionUpdate
     */
    formatVersion: number;
}


/**
 * @export
 */
export const UpgradeFormatVersionUpdateActionEnum = {
    UpgradeFormatVersion: 'upgrade-format-version'
} as const;
export type UpgradeFormatVersionUpdateActionEnum = typeof UpgradeFormatVersionUpdateActionEnum[keyof typeof UpgradeFormatVersionUpdateActionEnum];


/**
 * Check if a given object implements the UpgradeFormatVersionUpdate interface.
 */
export function instanceOfUpgradeFormatVersionUpdate(value: object): boolean {
    if (!('action' in value)) return false;
    if (!('formatVersion' in value)) return false;
    return true;
}

export function UpgradeFormatVersionUpdateFromJSON(json: any): UpgradeFormatVersionUpdate {
    return UpgradeFormatVersionUpdateFromJSONTyped(json, false);
}

export function UpgradeFormatVersionUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpgradeFormatVersionUpdate {
    if (json == null) {
        return json;
    }
    return {
        ...BaseUpdateFromJSONTyped(json, ignoreDiscriminator),
        'action': json['action'],
        'formatVersion': json['format-version'],
    };
}

export function UpgradeFormatVersionUpdateToJSON(value?: UpgradeFormatVersionUpdate | null): any {
    if (value == null) {
        return value;
    }
    return {
        ...BaseUpdateToJSON(value),
        'action': value['action'],
        'format-version': value['formatVersion'],
    };
}

