/* tslint:disable */
/* eslint-disable */
/**
 * Apache Iceberg REST Catalog API
 * Defines the specification for the first version of the REST Catalog API. Implementations should ideally support both Iceberg table specs v1 and v2, with priority given to v2.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ViewHistoryEntry
 */
export interface ViewHistoryEntry {
    /**
     * 
     * @type {number}
     * @memberof ViewHistoryEntry
     */
    versionId: number;
    /**
     * 
     * @type {number}
     * @memberof ViewHistoryEntry
     */
    timestampMs: number;
}

/**
 * Check if a given object implements the ViewHistoryEntry interface.
 */
export function instanceOfViewHistoryEntry(value: object): value is ViewHistoryEntry {
    if (!('versionId' in value) || value['versionId'] === undefined) return false;
    if (!('timestampMs' in value) || value['timestampMs'] === undefined) return false;
    return true;
}

export function ViewHistoryEntryFromJSON(json: any): ViewHistoryEntry {
    return ViewHistoryEntryFromJSONTyped(json, false);
}

export function ViewHistoryEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViewHistoryEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'versionId': json['version-id'],
        'timestampMs': json['timestamp-ms'],
    };
}

export function ViewHistoryEntryToJSON(json: any): ViewHistoryEntry {
    return ViewHistoryEntryToJSONTyped(json, false);
}

export function ViewHistoryEntryToJSONTyped(value?: ViewHistoryEntry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version-id': value['versionId'],
        'timestamp-ms': value['timestampMs'],
    };
}

